channels:
  - conda-forge

dependencies:
  - jupyterhub-singleuser

  # Everyone wants to use nbgitpuller for everything, so let's do that
  - nbgitpuller
  # Code server is a VS Code like editor for the browser
  - code-server>=4.0
  # Jupyter-vscode-proxy is a proxy for the code server
  - jupyter-vscode-proxy
  # Jupyter-server-proxy is a proxy for the jupyter server
  - jupyter-server-proxy
  # Install packages from pip
  - pip
  - pip:
    # Jupyter-ai is a package for AI-powered notebooks
    # Installed via pip to avoid langchain/typer version conflicts with conda
    - jupyter-ai[all]
    - globus-sdk
