#!/bin/bash

set -euo pipefail

# Define packages
declare -a packages=( ms-python.python svelte.svelte-vscode openai.chatgpt anthropic.claude-code )

# Install them
for package in "${packages[@]}"
do
  echo code-server --install-extension "${package}"
done